version: '3'
services:
  mongo-db:
    image: mongo
    restart: always
    env_file:
      - local.env
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
      - ./db/init-db.js:/docker-entrypoint-initdb.d/init-db.js
  react-app:
    build:
      context: ./ui
      dockerfile: ui.Dockerfile
    ports:
      - 5173:5173
    env_file:
      - common.env
    volumes:
      - ./ui:/app
  node-app:
    build:
      context: ./app
      dockerfile: app.Dockerfile
    ports:
      - 3000:3000
    env_file:
      - common.env
    volumes:
      - ./app:/app
volumes:
  mongodb-data: